spring:
  elasticsearch:
    host: ${ip}
    port: 9200
    username: "elastic" # 登录es的帐号
    password: "elastic" # 登录es的密码
    uris: http://${ip}:9200 # es路径
    connection-timeout: 2s
    socket-timeout: 2s


